---
name: Build Anki deck
on: [push, pull_request]
jobs:
  build-anki-deck:
    name: Build Anki deck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install sqlite
        run: sudo apt-get install sqlite3 unzip
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H:%M:%S')" >> "$GITHUB_OUTPUT"
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%s')" >> "$GITHUB_OUTPUT"
      - name: Test build Anki Deck
        run: >
          git clean -f -x -d
          && python generate.py --start 1 --stop 5 --page-size 2
          && unzip leetcode.apkg
          && sqlite3 collection.anki2 .schema
          && sqlite3 collection.anki2 .dump
        env:
          LEETCODE_SESSION_ID: ${{ secrets.LEETCODE_SESSION_ID }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
      - name: Test build Anki Deck (non-default output file)
        run: >
          git clean -f -x -d
          && python generate.py --stop 3 --output-file test.apkg
          && unzip test.apkg
          && sqlite3 collection.anki2 .schema
          && sqlite3 collection.anki2 .dump
        env:
          LEETCODE_SESSION_ID: ${{ secrets.LEETCODE_SESSION_ID }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
      - name: Test build Anki Deck with Amazon list id
        run: python generate.py --stop 10 --list-id 7p5x763
        env:
          LEETCODE_SESSION_ID: ${{ secrets.LEETCODE_SESSION_ID }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
      - name: Build Anki Deck
        run: python generate.py
        if: github.ref == 'refs/heads/master'
        env:
          LEETCODE_SESSION_ID: ${{ secrets.LEETCODE_SESSION_ID }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ github.ref_name }}-${{ steps.timestamp.outputs.timestamp }}
          name: >
            Anki Deck from ${{ github.ref }} on ${{ steps.date.outputs.date }}
          draft: true
          prerelease: true
          files: ./leetcode.apkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
